version: "3"
services:

  mysql-server:
    image: mysql:5.7
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    command: --character-set-server=utf8
    volumes:
      - ./db:/var/lib/mysql

  zabbix-server:
    image: zabbix/zabbix-server-mysql:${VERSION}
    restart: "always"
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: mysql-server
      DB_SERVER_PORT: 3306
      MYSQL_DATABASE: zabbix 
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_TIMEOUT: 30
    volumes:
      - ./weixin.sh:/usr/lib/zabbix/alertscripts/weixin.sh
      - ./curl:/usr/bin/curl

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:${VERSION}
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_SERVER_HOST: mysql-server
      DB_SERVER_PORT: 3306
      MYSQL_DATABASE: zabbix 
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      PHP_TZ: Asia/Shanghai
      ZBX_SERVER_HOST: zabbix-server 
#    volumes:
#      - ./web:/usr/share/zabbix/

        #  zabbix-agent:
        #      image: zabbix/zabbix-agent
        #      container_name: zabbix-server-agent
        #      ports:
        #        - '10050:10050'
        #      environment:
        #        ZBX_HOSTNAME: Zabbix server 
        #        ZBX_SERVER_HOST: 192.168.11.129
        #      volumes:
        #      - /Users/it/zabbix/zabbix_agentd.conf:/etc/zabbix/zabbix_agentd.conf
